config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  namespace :api do
    namespace :v1 do
      resources :events
    end
  end

  resources :pages, path: 'paginas'

  resources :financial_transactions, path: 'transparencia'
  resources :social_network_types
  resources :winners

  get "activities/index"
  get 'certificado', to: 'users#certified', as: 'certified'
  put 'name_alter', to: 'users#name_alter', as: 'name_alter'
  get 'uf_id_extenso', to: 'users#uf_id_extended', as: 'uf_id_extended'

  resources :images
  resources :albums
  resources :links, path: "links" do
    collection do
      get 'uteis'
    end
  end

  resources :gifts
  resources :link_categories
  resources :partners
  resources :events, path: 'eventos' do
    post :register, on: :member
    collection do
      post 'register'
      get 'index_admin'
      get 'presents'
      get 'user_present_new'
    end
    resources :registrations, controller: 'event_registrations'

  end
  resources :attachments
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks"}
  resources :users, only: [:show, :index]

  # get "/paginas/:pagina" => "paginas#show"
  get 'contact', to: 'messages#new', as: 'contact'
  post 'messages/subscribe', to: 'messages#subscribe'
  post 'contact', to: 'messages#create'
  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
  match "/422" => "errors#error422", via: [:get, :post, :patch, :delete]
  match "/500" => "errors#error500", via: [:get, :post, :patch, :delete]
end

app/models/link_category.rb
# == Schema Information
#
# Table name: link_categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class LinkCategory < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }
  resourcify
  has_many :links
end

app/controllers/link_categories_controller.rb
class LinkCategoriesController < ApplicationController
  before_action :set_link_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /link_categories
  # GET /link_categories.json
  def index
    @link_categories = LinkCategory.all
  end

  # GET /link_categories/1
  # GET /link_categories/1.json
  def show
  end

  # GET /link_categories/new
  def new
    @link_category = LinkCategory.new
  end

  # GET /link_categories/1/edit
  def edit
  end

  # POST /link_categories
  # POST /link_categories.json
  def create
    @link_category = LinkCategory.new(link_category_params)

    respond_to do |format|
      if @link_category.save
        format.html { redirect_to @link_category, notice: 'Link category was successfully created.' }
        format.json { render :show, status: :created, location: @link_category }
      else
        format.html { render :new }
        format.json { render json: @link_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /link_categories/1
  # PATCH/PUT /link_categories/1.json
  def update
    respond_to do |format|
      if @link_category.update(link_category_params)
        format.html { redirect_to @link_category, notice: 'Link category was successfully updated.' }
        format.json { render :show, status: :ok, location: @link_category }
      else
        format.html { render :edit }
        format.json { render json: @link_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /link_categories/1
  # DELETE /link_categories/1.json
  def destroy
    @link_category.destroy
    respond_to do |format|
      format.html { redirect_to link_categories_url, notice: 'Link category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link_category
      @link_category = LinkCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_category_params
      params.require(:link_category).permit(:name)
    end
end

app/views/link_categories/_collection.html.erb
<% collection.each do |resource| %>
    <tr id="<%= dom_id(resource) %>">
      <td><%= resource.name %></td>
      <td class="text-center">
        <% if current_user and current_user.admin? %>
            <%=resource.decorate.link_to_show%>
            <%=resource.decorate.link_to_edit%>
            <%=resource.decorate.link_to_delete%>
        <% end %>
      </td>
    </tr>
<% end %>

app/views/link_categories/_form.html.erb
<%= simple_form_for(@link_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-group form-actions">
  	<%= link_to I18n.t('misc.action.back'), link_categories_path, class: 'btn btn-sm btn-square btn-default' %>
    <%= f.button :submit, t('link_categories.form.submit'), class: 'btn btn-sm btn-square btn-primary' %>
  </div>
<% end %>

app/views/link_categories/_pagination.html.erb
<div class="paging_simple_numbers">
  <%= paginate collection, remote: true  %>
</div>

app/views/link_categories/edit.html.erb
<%= provide :page_title, I18n.t('link_categories.edit.header', resource: @link_category.try(:id) ) %>
<%= provide :breadcrumb do %>
  <li><%= link_to  I18n.t('activerecord.models.link_category.other'), link_categories_path %></li>
  <li><%= link_to  @link_category.try(:id), @link_category %></li>
  <li><%= I18n.t('link_categories.edit.header', resource: @link_category.try(:id) ) %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= t('link_categories.edit.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-header text-right">
        <h3 class="block-title">
        </h3>
        <span >
          <%= link_to I18n.t('link_categories.new.new'), new_link_category_path, class: 'btn btn-sm btn-square btn-success' %>
        </span>
      </div>
      <div class="block-content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</main>

app/views/link_categories/index.html.erb
<%= provide :page_title, I18n.t('link_categories.index.header') %>
<%= provide :breadcrumb do %>
  <li><%= I18n.t('activerecord.models.link_category.other') %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= t('link_categories.index.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-header text-right">
        <h3 class="block-title">
        </h3>
        <span >
          <%= link_to I18n.t('link_categories.new.new'), new_link_category_path, class: 'btn btn-sm btn-square btn-success' %>
        </span>
      </div>
      <div class="block-content">
        <table class="table table-striped">
            <thead>
                <tr>
                  <th><%= t('activerecord.attributes.link_category.name') %></th>
                  <th class="text-center" style="width: 150px;"><%=t 'misc.actions' %></th>
                </tr>
            </thead>
            <tbody id='link_categories'>
              <%= render 'collection', collection: @link_categories %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/link_categories/index.js.erb
$("#link_categories").html("<%=j render 'collection', collection: @link_categories %>");
$("#pagination").html("<%=j render 'pagination', collection: @link_categories %>");

app/views/link_categories/new.html.erb
<%= provide :page_title, I18n.t('link_categories.new.header') %>
<%= provide :breadcrumb do %>
  <li><%= link_to  t('activerecord.models.link_category.other'), link_categories_path %></li>
  <li><%=t 'link_categories.new.header' %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= I18n.t('link_categories.new.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</main>

app/views/link_categories/show.html.erb
<%= provide :page_title, I18n.t('link_categories.show.header', resource: @link_category.try(:id)) %>
<%= provide :breadcrumb do %>
    <li><%= link_to I18n.t('activerecord.models.link_category.other'), link_categories_path %></li>
    <li><%= link_to @link_category.try(:id), @link_category %></li>
    <li><%= I18n.t('link_categories.show.header', resource: @link_category.try(:id)) %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= t('link_categories.show.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-header text-right">
        <h3 class="block-title">
        </h3>
        <span>
          <%= link_to I18n.t('link_categories.new.new'), new_link_category_path, class: 'btn btn-sm btn-square btn-success' %>
        </span>
      </div>
      <div class="block-content">
        <div class="row">

          <div class="col-sm-12">
            <table class="table table-striped">
              <thead>
              </thead>
              <tbody>
              <tr>
                <td><strong><%= t 'activerecord.attributes.link_category.name' %>:</strong></td>
                <td><%= @link_category.name %></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">

          <div class="col-sm-4 ">
            <%= link_to I18n.t('misc.action.back'), link_categories_path, class: 'btn btn-default' %>
            <%= link_to I18n.t('misc.action.edit'), edit_link_category_path(@link_category), class: 'btn btn-warning' %>
            <%= link_to I18n.t('misc.action.destroy'), link_category_path(@link_category), method: :destroy, data: {confirm: I18n.t('link_categories.show.remover')}, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>