config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  namespace :api do
    namespace :v1 do
      resources :events
    end
  end

  resources :pages, path: 'paginas'

  resources :financial_transactions, path: 'transparencia'
  resources :social_network_types
  resources :winners

  get "activities/index"
  get 'certificado', to: 'users#certified', as: 'certified'
  put 'name_alter', to: 'users#name_alter', as: 'name_alter'
  get 'uf_id_extenso', to: 'users#uf_id_extended', as: 'uf_id_extended'

  resources :images
  resources :albums
  resources :links, path: "links" do
    collection do
      get 'uteis'
    end
  end

  resources :gifts
  resources :link_categories
  resources :partners
  resources :events, path: 'eventos' do
    post :register, on: :member
    collection do
      post 'register'
      get 'index_admin'
      get 'presents'
      get 'user_present_new'
    end
    resources :registrations, controller: 'event_registrations'

  end
  resources :attachments
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks"}
  resources :users, only: [:show, :index]

  # get "/paginas/:pagina" => "paginas#show"
  get 'contact', to: 'messages#new', as: 'contact'
  post 'messages/subscribe', to: 'messages#subscribe'
  post 'contact', to: 'messages#create'
  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
  match "/422" => "errors#error422", via: [:get, :post, :patch, :delete]
  match "/500" => "errors#error500", via: [:get, :post, :patch, :delete]
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  album_id   :integer
#  asset      :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_images_on_album_id  (album_id)
#
# Foreign Keys
#
#  fk_rails_...  (album_id => albums.id)
#

class Image < ActiveRecord::Base

  mount_uploader :asset, AttachmentsUploader
  belongs_to :album
  validates_presence_of :title

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:album_id, :asset, :title)
    end
end

app/views/images/_collection.html.erb
<% collection.each do |resource| %>
    <tr id="<%= dom_id(resource)%>">
              <td><%= resource.album %></td>
              <td><%= resource.asset %></td>
              <td><%= resource.title %></td>
            <td class="text-center">
        <div class="btn-group">
           <%= link_to image_path(resource), data: { toggle: 'tooltip', original_title: I18n.t('misc.action.show')}, title: '', class: "btn btn-xs btn-default" do %>
             <i class="fa fa-list"></i>
           <% end %>
             <%= link_to edit_image_path(resource) , data: { toggle: 'tooltip', original_title: I18n.t('misc.action.edit')}, title: '', class: "btn btn-xs btn-default" do %>
             <i class="fa fa-pencil"></i>
           <% end %>
             <%= link_to image_path(resource) , data: { toggle: 'tooltip', original_title: I18n.t('misc.action.destroy')}, title: '', class: "btn btn-xs btn-default" do %>
             <i class="fa fa-times"></i>
           <% end %> 
        </div>
      </td>
    </tr>
<% end %>

app/views/images/_form.html.erb
<%= simple_form_for(@image) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :album %>
    <%= f.input :asset %>
    <%= f.input :title %>
  </div>

  <div class="form-group form-actions">
  	<%= link_to I18n.t('misc.action.back'), images_path, class: 'btn btn-sm btn-square btn-default' %> 
    <%= f.button :submit, class: 'btn btn-sm btn-square btn-primary' %>
  </div>
<% end %>

app/views/images/_pagination.html.erb
<div class="paging_simple_numbers">
  <%= paginate collection, remote: true  %>
</div>

app/views/images/edit.html.erb
<%= provide :page_title, I18n.t('images.edit.header', resource: @image.try(:id) ) %>
<%= provide :breadcrumb do %>
  <li><%= link_to  I18n.t('activerecord.models.image.other'), images_path %></li>
  <li><%= link_to  @image.try(:id), @image %></li>
  <li><%= I18n.t('images.edit.header', resource: @image.try(:id) ) %></li>
<% end %>

<div class="row">
  <div class="block">
    <div class="block-header">
        <h3 class="block-title"><%= I18n.t('images.new.block_header') %></h3>
    </div>
    <div class="block-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/images/index.html.erb
<%= provide :page_title, I18n.t('images.index.header') %>
<%= provide :breadcrumb do %>
  <li><%= I18n.t('activerecord.models.image.other') %></li>
<% end %>

<div class="block">
  <div class="block-header">
      <h3 class="block-title"><%= I18n.t('images.index.block_header') %></h3>
      <div class="block-options">
        <%= link_to I18n.t('misc.action.new'), new_image_path, class: 'btn btn-sm btn-square btn-success' %>
      </div>
  </div>
  <div class="block-content">
    <table class="table table-striped">
        <thead>
            <tr>
                          <th><%=t 'activerecord.attributes.image.album' %></th>
                          <th><%=t 'activerecord.attributes.image.asset' %></th>
                          <th><%=t 'activerecord.attributes.image.title' %></th>
                          <th class="text-center" style="width: 100px;"><%=t 'misc.actions' %></th>
            </tr>
        </thead>
        <tbody id='images'>
          <%= render 'collection', collection: @images %> 
        </tbody>
    </table>
    
    <div class="dataTables_paginate paging_simple_numbers"  id="pagination">
      <%#= render 'pagination', collection: @images %>
    </div>
    
  </div>
</div>

app/views/images/index.js.erb
$("#images").html("<%=j render 'collection', collection: @images %>");
$("#pagination").html("<%=j render 'pagination', collection: @images %>");

app/views/images/new.html.erb
<%= provide :page_title, I18n.t('images.new.header') %>
<%= provide :breadcrumb do %>
  <li><%= link_to  t('activerecord.models.image.other'), images_path %></li>
  <li><%=t 'images.new.header' %></li>
<% end %>

<div class="row">
  <div class="block">
    <div class="block-header">
        <h3 class="block-title"><%= I18n.t('images.new.block_header') %></h3>
    </div>
    <div class="block-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/images/show.html.erb
<%= provide :page_title, I18n.t('images.show.header', resource: @image.try(:id) ) %>
<%= provide :breadcrumb do %>
  <li><%= link_to  I18n.t('activerecord.models.image.other'), images_path %></li>
  <li><%= link_to  @image.try(:id), @image %></li>
  <li><%= I18n.t('images.show.header', resource: @image.try(:id) ) %></li>
<% end %>

<div class="panel">
  <div class="panel-heading">
    <h3 class="panel-title"><%= I18n.t('images.show.header', resource: @image.try(:id)) %></h3>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        </thead>
        <tbody>
                  <tr>
            <td><strong><%=t 'activerecord.attributes.image.album' %>:</strong></td>
             <td><%= @image.album %></td>
          </tr>   
                  <tr>
            <td><strong><%=t 'activerecord.attributes.image.asset' %>:</strong></td>
             <td><%= @image.asset %></td>
          </tr>   
                  <tr>
            <td><strong><%=t 'activerecord.attributes.image.title' %>:</strong></td>
             <td><%= @image.title %></td>
          </tr>   
                </tbody>
      </table>
    </div>
  </div>
  <div class="panel-footer">
    <div class="row">
      <div class="col-sm-7">
        <%= link_to I18n.t('misc.action.back'), images_path, class: 'btn btn-default' %>
        <%= link_to I18n.t('misc.action.edit'),edit_image_path(@image), class: 'btn btn-warning' %>
        <%= link_to I18n.t('misc.action.destroy'),image_path(@image), method: :destroy, data: {confirm: I18n.t('misc.actions.confirm') }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>